source 'https://rubygems.org'
gem 'activeadmin', '>= 1.4.3'
gem 'jquery-rails', '>= 0'
gem 'kaminari-mongoid', '>= 0'
gem 'mongoid', '>= 6.0', '< 8.a'
gem 'sass-rails', '>= 3.1.4'
gem 'rails', '= 4.1'